env:
  browser: true
  es2021: true
plugins: ['@typescript-eslint']
extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended']
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
root: true
rules:
  {
    '@typescript-eslint/no-unused-vars':
      [
        'error',
        {
          'argsIgnorePattern': '^_',
          'varsIgnorePattern': '^_',
          'caughtErrorsIgnorePattern': '^_'
        }
      ],
    '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  }
