version: '1.0'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      -  db:/var/lib/postgres/data
      -  ./src/db/sql/create-access-to-entities.sql:/docker-entrypoint-initdb.d/create-access-to-entities.sql
      -  ./src/db/sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
  
  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redisPassword
    volumes:
      - cache:/data
      
  gqlms:
    container_name: gqlms
    build:
      context: .
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: gqlms      
    links:
      - db
    volumes:
      - './:/server'

volumes:
    cache:
      driver: local
    db:
      driver: local
  